// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Activity.StreamNamespace;
using XbyOpenApi.Core.Client.Two.Activity.Subscriptions;
namespace XbyOpenApi.Core.Client.Two.Activity
{
  /// <summary>
  /// Builds and executes requests for operations under \2\activity
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ActivityRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The stream property</summary>
    public global::XbyOpenApi.Core.Client.Two.Activity.StreamNamespace.StreamRequestBuilder Stream
    {
      get => new global::XbyOpenApi.Core.Client.Two.Activity.StreamNamespace.StreamRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The subscriptions property</summary>
    public global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.SubscriptionsRequestBuilder Subscriptions
    {
      get => new global::XbyOpenApi.Core.Client.Two.Activity.Subscriptions.SubscriptionsRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Activity.ActivityRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ActivityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/activity", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Activity.ActivityRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ActivityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/activity", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
