// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Two.Users.Reposts_of_me
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum GetExpansionsQueryParameterType
#pragma warning restore CS1591
  {
    [EnumMember(Value = "article.cover_media")]
#pragma warning disable CS1591
    ArticleCover_media,
#pragma warning restore CS1591
    [EnumMember(Value = "article.media_entities")]
#pragma warning disable CS1591
    ArticleMedia_entities,
#pragma warning restore CS1591
    [EnumMember(Value = "attachments.media_keys")]
#pragma warning disable CS1591
    AttachmentsMedia_keys,
#pragma warning restore CS1591
    [EnumMember(Value = "attachments.media_source_tweet")]
#pragma warning disable CS1591
    AttachmentsMedia_source_tweet,
#pragma warning restore CS1591
    [EnumMember(Value = "attachments.poll_ids")]
#pragma warning disable CS1591
    AttachmentsPoll_ids,
#pragma warning restore CS1591
    [EnumMember(Value = "author_id")]
#pragma warning disable CS1591
    Author_id,
#pragma warning restore CS1591
    [EnumMember(Value = "edit_history_post_ids")]
#pragma warning disable CS1591
    Edit_history_post_ids,
#pragma warning restore CS1591
    [EnumMember(Value = "entities.mentions.username")]
#pragma warning disable CS1591
    EntitiesMentionsUsername,
#pragma warning restore CS1591
    [EnumMember(Value = "geo.place_id")]
#pragma warning disable CS1591
    GeoPlace_id,
#pragma warning restore CS1591
    [EnumMember(Value = "in_reply_to_user_id")]
#pragma warning disable CS1591
    In_reply_to_user_id,
#pragma warning restore CS1591
    [EnumMember(Value = "referenced_posts")]
#pragma warning disable CS1591
    Referenced_posts,
#pragma warning restore CS1591
    [EnumMember(Value = "username")]
#pragma warning disable CS1591
    Username,
#pragma warning restore CS1591
  }
}
