// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Dm_conversations.Media.Item.Item;
namespace XbyOpenApi.Core.Client.Two.Dm_conversations.Media.Item
{
  /// <summary>
  /// Builds and executes requests for operations under \2\dm_conversations\media\{dm_id}
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class WithDm_ItemRequestBuilder : BaseRequestBuilder
  {
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.dm_conversations.media.item.item collection</summary>
    /// <param name="position">Unique identifier of the item</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Dm_conversations.Media.Item.Item.WithMedia_ItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Dm_conversations.Media.Item.Item.WithMedia_ItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("media_id", position);
        return new global::XbyOpenApi.Core.Client.Two.Dm_conversations.Media.Item.Item.WithMedia_ItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Dm_conversations.Media.Item.WithDm_ItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public WithDm_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/dm_conversations/media/{dm_id}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Dm_conversations.Media.Item.WithDm_ItemRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public WithDm_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/dm_conversations/media/{dm_id}", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
