// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Articles.Draft;
using XbyOpenApi.Core.Client.Two.Articles.Item;
namespace XbyOpenApi.Core.Client.Two.Articles
{
  /// <summary>
  /// Builds and executes requests for operations under \2\articles
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ArticlesRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The draft property</summary>
    public global::XbyOpenApi.Core.Client.Two.Articles.Draft.DraftRequestBuilder Draft
    {
      get => new global::XbyOpenApi.Core.Client.Two.Articles.Draft.DraftRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.articles.item collection</summary>
    /// <param name="position">Unique identifier of the item</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Articles.Item.WithArticle_ItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Articles.Item.WithArticle_ItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("article_id", position);
        return new global::XbyOpenApi.Core.Client.Two.Articles.Item.WithArticle_ItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Articles.ArticlesRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ArticlesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/articles", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Articles.ArticlesRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ArticlesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/articles", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
