// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Two.Broadcasts
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum GetBroadcastFieldsQueryParameterType
#pragma warning restore CS1591
  {
    [EnumMember(Value = "available_for_replay")]
#pragma warning disable CS1591
    Available_for_replay,
#pragma warning restore CS1591
    [EnumMember(Value = "broadcast_id")]
#pragma warning disable CS1591
    Broadcast_id,
#pragma warning restore CS1591
    [EnumMember(Value = "chat_option")]
#pragma warning disable CS1591
    Chat_option,
#pragma warning restore CS1591
    [EnumMember(Value = "created_at_ms")]
#pragma warning disable CS1591
    Created_at_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "end_ms")]
#pragma warning disable CS1591
    End_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "height")]
#pragma warning disable CS1591
    Height,
#pragma warning restore CS1591
    [EnumMember(Value = "id")]
#pragma warning disable CS1591
    Id,
#pragma warning restore CS1591
    [EnumMember(Value = "image_url")]
#pragma warning disable CS1591
    Image_url,
#pragma warning restore CS1591
    [EnumMember(Value = "image_url_medium")]
#pragma warning disable CS1591
    Image_url_medium,
#pragma warning restore CS1591
    [EnumMember(Value = "image_url_small")]
#pragma warning disable CS1591
    Image_url_small,
#pragma warning restore CS1591
    [EnumMember(Value = "is_high_latency")]
#pragma warning disable CS1591
    Is_high_latency,
#pragma warning restore CS1591
    [EnumMember(Value = "language")]
#pragma warning disable CS1591
    Language,
#pragma warning restore CS1591
    [EnumMember(Value = "media_key")]
#pragma warning disable CS1591
    Media_key,
#pragma warning restore CS1591
    [EnumMember(Value = "scheduled_end_ms")]
#pragma warning disable CS1591
    Scheduled_end_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "scheduled_start_ms")]
#pragma warning disable CS1591
    Scheduled_start_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "share_url")]
#pragma warning disable CS1591
    Share_url,
#pragma warning restore CS1591
    [EnumMember(Value = "source_id")]
#pragma warning disable CS1591
    Source_id,
#pragma warning restore CS1591
    [EnumMember(Value = "start_ms")]
#pragma warning disable CS1591
    Start_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "state")]
#pragma warning disable CS1591
    State,
#pragma warning restore CS1591
    [EnumMember(Value = "title")]
#pragma warning disable CS1591
    Title,
#pragma warning restore CS1591
    [EnumMember(Value = "total_watched")]
#pragma warning disable CS1591
    Total_watched,
#pragma warning restore CS1591
    [EnumMember(Value = "total_watching")]
#pragma warning disable CS1591
    Total_watching,
#pragma warning restore CS1591
    [EnumMember(Value = "tweet_id")]
#pragma warning disable CS1591
    Tweet_id,
#pragma warning restore CS1591
    [EnumMember(Value = "twitter_user_id")]
#pragma warning disable CS1591
    Twitter_user_id,
#pragma warning restore CS1591
    [EnumMember(Value = "updated_at_ms")]
#pragma warning disable CS1591
    Updated_at_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "width")]
#pragma warning disable CS1591
    Width,
#pragma warning restore CS1591
  }
}
