// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Tweets.Search.All;
using XbyOpenApi.Core.Client.Two.Tweets.Search.Recent;
using XbyOpenApi.Core.Client.Two.Tweets.Search.StreamNamespace;
using XbyOpenApi.Core.Client.Two.Tweets.Search.Webhooks;
namespace XbyOpenApi.Core.Client.Two.Tweets.Search
{
  /// <summary>
  /// Builds and executes requests for operations under \2\tweets\search
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class SearchRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The all property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Search.All.AllRequestBuilder All
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Search.All.AllRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The recent property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Search.Recent.RecentRequestBuilder Recent
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Search.Recent.RecentRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The stream property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Search.StreamNamespace.StreamRequestBuilder Stream
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Search.StreamNamespace.StreamRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The webhooks property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Search.Webhooks.WebhooksRequestBuilder Webhooks
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Search.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Tweets.Search.SearchRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public SearchRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/search", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Tweets.Search.SearchRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public SearchRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/search", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
