// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Communities.Item;
using XbyOpenApi.Core.Client.Two.Communities.Search;
namespace XbyOpenApi.Core.Client.Two.Communities
{
  /// <summary>
  /// Builds and executes requests for operations under \2\communities
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class CommunitiesRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The search property</summary>
    public global::XbyOpenApi.Core.Client.Two.Communities.Search.SearchRequestBuilder Search
    {
      get => new global::XbyOpenApi.Core.Client.Two.Communities.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.communities.item collection</summary>
    /// <param name="position">The ID of the Community.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Communities.Item.CommunitiesItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Communities.Item.CommunitiesItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("id", position);
        return new global::XbyOpenApi.Core.Client.Two.Communities.Item.CommunitiesItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Communities.CommunitiesRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public CommunitiesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/communities", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Communities.CommunitiesRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public CommunitiesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/communities", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
