// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
using XbyOpenApi.Core.Client.Models;
using XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.Item;
using XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.Mutes;
namespace XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat
{
  /// <summary>
  /// Builds and executes requests for operations under \2\broadcasts\{id}\chat
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class ChatRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The mutes property</summary>
    public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.Mutes.MutesRequestBuilder Mutes
    {
      get => new global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.Mutes.MutesRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.broadcasts.item.chat.item collection</summary>
    /// <param name="position">Unique identifier of the item</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.Item.WithMessage_ItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.Item.WithMessage_ItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("message_id", position);
        return new global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.Item.WithMessage_ItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/broadcasts/{id}/chat{?broadcast_chat_message%2Efields,expansions,max_results*,pagination_token*,user%2Efields}", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public ChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/broadcasts/{id}/chat{?broadcast_chat_message%2Efields,expansions,max_results*,pagination_token*,user%2Efields}", rawUrl)
    {
    }
    /// <summary>
    /// Returns newest-first chat messages for a broadcast owned by the authenticated user.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.GetBroadcastChatResponse"/></returns>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.GetBroadcastChatResponse?> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder.ChatRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.GetBroadcastChatResponse> GetAsync(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder.ChatRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      var requestInfo = ToGetRequestInformation(requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.GetBroadcastChatResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.GetBroadcastChatResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Posts a chat message to a running broadcast, attributed to the authenticated user.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.SendBroadcastChatResponse"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
    /// <exception cref="global::XbyOpenApi.Core.Client.Models.Error">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public async Task<global::XbyOpenApi.Core.Client.Models.SendBroadcastChatResponse?> PostAsync(global::XbyOpenApi.Core.Client.Models.SendBroadcastChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#nullable restore
#else
    public async Task<global::XbyOpenApi.Core.Client.Models.SendBroadcastChatResponse> PostAsync(global::XbyOpenApi.Core.Client.Models.SendBroadcastChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = ToPostRequestInformation(body, requestConfiguration);
      var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "XXX", global::XbyOpenApi.Core.Client.Models.Error.CreateFromDiscriminatorValue },
            };
      return await RequestAdapter.SendAsync<global::XbyOpenApi.Core.Client.Models.SendBroadcastChatResponse>(requestInfo, global::XbyOpenApi.Core.Client.Models.SendBroadcastChatResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
    }
    /// <summary>
    /// Returns newest-first chat messages for a broadcast owned by the authenticated user.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder.ChatRequestBuilderGetQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder.ChatRequestBuilderGetQueryParameters>> requestConfiguration = default)
    {
#endif
      var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      return requestInfo;
    }
    /// <summary>
    /// Posts a chat message to a running broadcast, attributed to the authenticated user.
    /// </summary>
    /// <returns>A <see cref="RequestInformation"/></returns>
    /// <param name="body">The request body</param>
    /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public RequestInformation ToPostRequestInformation(global::XbyOpenApi.Core.Client.Models.SendBroadcastChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
    {
#nullable restore
#else
    public RequestInformation ToPostRequestInformation(global::XbyOpenApi.Core.Client.Models.SendBroadcastChatRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
    {
#endif
      if (ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
      var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
      requestInfo.Configure(requestConfiguration);
      requestInfo.Headers.TryAdd("Accept", "application/json");
      requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
      return requestInfo;
    }
    /// <summary>
    /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder"/></returns>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder WithUrl(string rawUrl)
    {
      return new global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.ChatRequestBuilder(rawUrl, RequestAdapter);
    }
    /// <summary>
    /// Returns newest-first chat messages for a broadcast owned by the authenticated user.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatRequestBuilderGetQueryParameters
    {
      /// <summary>A comma separated list of BroadcastChatMessage fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("broadcast_chat_message%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.GetBroadcast_chat_messageFieldsQueryParameterType[]? BroadcastChatMessageFields { get; set; }
#nullable restore
#else
      [QueryParameter("broadcast_chat_message%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.GetBroadcast_chat_messageFieldsQueryParameterType[] BroadcastChatMessageFields { get; set; }
#endif
      /// <summary>A comma separated list of fields to expand.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("expansions")]
      public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.GetExpansionsQueryParameterType[]? Expansions { get; set; }
#nullable restore
#else
      [QueryParameter("expansions")]
      public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.GetExpansionsQueryParameterType[] Expansions { get; set; }
#endif
      [QueryParameter("max_results")]
      public int? MaxResults { get; set; }
      /// <summary>A 64-bit signed integer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("pagination_token")]
      public string? PaginationToken { get; set; }
#nullable restore
#else
      [QueryParameter("pagination_token")]
      public string PaginationToken { get; set; }
#endif
      /// <summary>A comma separated list of User fields to display.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      [QueryParameter("user%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.GetUserFieldsQueryParameterType[]? UserFields { get; set; }
#nullable restore
#else
      [QueryParameter("user%2Efields")]
      public global::XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat.GetUserFieldsQueryParameterType[] UserFields { get; set; }
#endif
    }
  }
}
#pragma warning restore CS0618
