// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Two.Broadcasts.Item.Chat
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum GetBroadcast_chat_messageFieldsQueryParameterType
#pragma warning restore CS1591
  {
    [EnumMember(Value = "author_name")]
#pragma warning disable CS1591
    Author_name,
#pragma warning restore CS1591
    [EnumMember(Value = "author_username")]
#pragma warning disable CS1591
    Author_username,
#pragma warning restore CS1591
    [EnumMember(Value = "broadcast_id")]
#pragma warning disable CS1591
    Broadcast_id,
#pragma warning restore CS1591
    [EnumMember(Value = "created_at_ms")]
#pragma warning disable CS1591
    Created_at_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "id")]
#pragma warning disable CS1591
    Id,
#pragma warning restore CS1591
    [EnumMember(Value = "reply_to")]
#pragma warning disable CS1591
    Reply_to,
#pragma warning restore CS1591
    [EnumMember(Value = "text")]
#pragma warning disable CS1591
    Text,
#pragma warning restore CS1591
  }
}
