// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.All;
using XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.Item;
namespace XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions
{
  /// <summary>
  /// Builds and executes requests for operations under \2\account_activity\webhooks\{webhook_id}\subscriptions
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class SubscriptionsRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The all property</summary>
    public global::XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.All.AllRequestBuilder All
    {
      get => new global::XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.All.AllRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.account_activity.webhooks.item.subscriptions.item collection</summary>
    /// <param name="position">User ID to unsubscribe from.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.Item.WithUser_ItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.Item.WithUser_ItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("user_id", position);
        return new global::XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.Item.WithUser_ItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.SubscriptionsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public SubscriptionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/account_activity/webhooks/{webhook_id}/subscriptions", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Account_activity.Webhooks.Item.Subscriptions.SubscriptionsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public SubscriptionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/account_activity/webhooks/{webhook_id}/subscriptions", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
