// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Two.Chat.Conversations.Item
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum GetChat_conversationFieldsQueryParameterType
#pragma warning restore CS1591
  {
    [EnumMember(Value = "created_at")]
#pragma warning disable CS1591
    Created_at,
#pragma warning restore CS1591
    [EnumMember(Value = "group_avatar_url")]
#pragma warning disable CS1591
    Group_avatar_url,
#pragma warning restore CS1591
    [EnumMember(Value = "group_name")]
#pragma warning disable CS1591
    Group_name,
#pragma warning restore CS1591
    [EnumMember(Value = "id")]
#pragma warning disable CS1591
    Id,
#pragma warning restore CS1591
    [EnumMember(Value = "is_muted")]
#pragma warning disable CS1591
    Is_muted,
#pragma warning restore CS1591
    [EnumMember(Value = "message_ttl_ms")]
#pragma warning disable CS1591
    Message_ttl_ms,
#pragma warning restore CS1591
    [EnumMember(Value = "screen_capture_blocking_enabled")]
#pragma warning disable CS1591
    Screen_capture_blocking_enabled,
#pragma warning restore CS1591
    [EnumMember(Value = "screen_capture_detection_enabled")]
#pragma warning disable CS1591
    Screen_capture_detection_enabled,
#pragma warning restore CS1591
    [EnumMember(Value = "type")]
#pragma warning disable CS1591
    Type,
#pragma warning restore CS1591
    [EnumMember(Value = "updated_at")]
#pragma warning disable CS1591
    Updated_at,
#pragma warning restore CS1591
  }
}
