// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Tweets.Counts.All;
using XbyOpenApi.Core.Client.Two.Tweets.Counts.Recent;
namespace XbyOpenApi.Core.Client.Two.Tweets.Counts
{
  /// <summary>
  /// Builds and executes requests for operations under \2\tweets\counts
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class CountsRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The all property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Counts.All.AllRequestBuilder All
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Counts.All.AllRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The recent property</summary>
    public global::XbyOpenApi.Core.Client.Two.Tweets.Counts.Recent.RecentRequestBuilder Recent
    {
      get => new global::XbyOpenApi.Core.Client.Two.Tweets.Counts.Recent.RecentRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Tweets.Counts.CountsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public CountsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/counts", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Tweets.Counts.CountsRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public CountsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/tweets/counts", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
