// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// Video metric counts for this bucket. Counters are integers when the backend value parses as a number, otherwise the original string is preserved.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class Analytics_metrics : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks? CtaUrlClicks { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks CtaUrlClicks { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks? CtaWatchClicks { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks CtaWatchClicks { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25? Playback25 { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25 Playback25 { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50? Playback50 { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50 Playback50 { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75? Playback75 { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75 Playback75 { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete? PlaybackComplete { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete PlaybackComplete { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start? PlaybackStart { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start PlaybackStart { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap? PlayFromTap { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap PlayFromTap { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views? VideoViews { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views VideoViews { get; set; }
#endif
    /// <summary>A video metric counter: an integer when the backend value parses as a number, otherwise the original string.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms? WatchTimeMs { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms WatchTimeMs { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics"/> and sets the default values.
    /// </summary>
    public Analytics_metrics()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.Analytics_metrics();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "cta_url_clicks", n => { CtaUrlClicks = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks.CreateFromDiscriminatorValue); } },
                { "cta_watch_clicks", n => { CtaWatchClicks = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks.CreateFromDiscriminatorValue); } },
                { "play_from_tap", n => { PlayFromTap = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap.CreateFromDiscriminatorValue); } },
                { "playback25", n => { Playback25 = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25.CreateFromDiscriminatorValue); } },
                { "playback50", n => { Playback50 = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50.CreateFromDiscriminatorValue); } },
                { "playback75", n => { Playback75 = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75.CreateFromDiscriminatorValue); } },
                { "playback_complete", n => { PlaybackComplete = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete.CreateFromDiscriminatorValue); } },
                { "playback_start", n => { PlaybackStart = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start.CreateFromDiscriminatorValue); } },
                { "video_views", n => { VideoViews = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views.CreateFromDiscriminatorValue); } },
                { "watch_time_ms", n => { WatchTimeMs = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms>(global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms.CreateFromDiscriminatorValue); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks>("cta_url_clicks", CtaUrlClicks);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks>("cta_watch_clicks", CtaWatchClicks);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25>("playback25", Playback25);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50>("playback50", Playback50);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75>("playback75", Playback75);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete>("playback_complete", PlaybackComplete);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start>("playback_start", PlaybackStart);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap>("play_from_tap", PlayFromTap);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views>("video_views", VideoViews);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms>("watch_time_ms", WatchTimeMs);
      writer.WriteAdditionalData(AdditionalData);
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_cta_url_clicks : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_url_clicks();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_cta_watch_clicks : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_cta_watch_clicks();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_play_from_tap : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_play_from_tap();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_playback_complete : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_complete();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_playback_start : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback_start();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_playback25 : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25 CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback25();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_playback50 : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50 CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback50();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_playback75 : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75 CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_playback75();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_video_views : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_video_views();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="long"/>, <see cref="string"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Analytics_metrics_watch_time_ms : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="long"/></summary>
      public long? Int64 { get; set; }
      /// <summary>Composed type representation for type <see cref="string"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public string? String { get; set; }
#nullable restore
#else
      public string String { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
        var result = new global::XbyOpenApi.Core.Client.Models.Analytics_metrics.Analytics_metrics_watch_time_ms();
        if (parseNode.GetLongValue() is long int64Value)
        {
          result.Int64 = int64Value;
        }
        else if (parseNode.GetStringValue() is string stringValue)
        {
          result.String = stringValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Int64 != null)
        {
          writer.WriteLongValue(null, Int64);
        }
        else if (String != null)
        {
          writer.WriteStringValue(null, String);
        }
      }
    }
  }
}
#pragma warning restore CS0618
