// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class AppendMediaUploadRequest : IParsable
#pragma warning restore CS1591
  {
    /// <summary>The media chunk to upload.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media? Media { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media Media { get; set; }
#endif
    /// <summary>The index of this segment in the upload sequence.</summary>
    public int? SegmentIndex { get; set; }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "media", n => { Media = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media>(global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media.CreateFromDiscriminatorValue); } },
                { "segment_index", n => { SegmentIndex = n.GetIntValue(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media>("media", Media);
      writer.WriteIntValue("segment_index", SegmentIndex);
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="byte[]"/>, <see cref="byte[]"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AppendMediaUploadRequest_media : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="byte[]"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public byte[]? Base64 { get; set; }
#nullable restore
#else
      public byte[] Base64 { get; set; }
#endif
      /// <summary>Composed type representation for type <see cref="byte[]"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public byte[]? Binary { get; set; }
#nullable restore
#else
      public byte[] Binary { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var result = new global::XbyOpenApi.Core.Client.Models.AppendMediaUploadRequest.AppendMediaUploadRequest_media();
        if (parseNode.GetByteArrayValue() is byte[] base64Value)
        {
          result.Base64 = base64Value;
        }
        else if (parseNode.GetByteArrayValue() is byte[] binaryValue)
        {
          result.Binary = binaryValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Base64 != null)
        {
          writer.WriteByteArrayValue(null, Base64);
        }
        else if (Binary != null)
        {
          writer.WriteByteArrayValue(null, Binary);
        }
      }
    }
  }
}
#pragma warning restore CS0618
