// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class ArticleCreateDraftContentStateEntitiesValue : IParsable
#pragma warning restore CS1591
  {
    /// <summary>The data property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValueData? Data { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValueData Data { get; set; }
#endif
    /// <summary>Whether the entity can be edited. Recommended: immutable for post, image, divider, latex; mutable for link and markdown (matches the in-app Articles composer).</summary>
    public global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue_mutability? Mutability { get; set; }
    /// <summary>The entity type. markdown carries code blocks, GFM tables, and other Markdown;          emoji maps to backend TWEMOJI (Twemoji is internal); divider is a horizontal rule;          latex renders TeX from the block text. Tables are not a separate enum value — use          type markdown with a pipe table in data.markdown.</summary>
    public global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue_type? Type { get; set; }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "data", n => { Data = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValueData>(global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValueData.CreateFromDiscriminatorValue); } },
                { "mutability", n => { Mutability = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue_mutability>(); } },
                { "type", n => { Type = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue_type>(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValueData>("data", Data);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue_mutability>("mutability", Mutability);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.ArticleCreateDraftContentStateEntitiesValue_type>("type", Type);
    }
  }
}
#pragma warning restore CS0618
