// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>Who can reply to the poll Tweet. Accepted for compatibility; it carries no backend argument and is dropped before the mutation is issued (see `translate_body`).</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum CreatePostsPoll_reply_settings
  {
    [EnumMember(Value = "following")]
#pragma warning disable CS1591
    Following,
#pragma warning restore CS1591
    [EnumMember(Value = "mentionedUsers")]
#pragma warning disable CS1591
    MentionedUsers,
#pragma warning restore CS1591
    [EnumMember(Value = "subscribers")]
#pragma warning disable CS1591
    Subscribers,
#pragma warning restore CS1591
    [EnumMember(Value = "verified")]
#pragma warning disable CS1591
    Verified,
#pragma warning restore CS1591
  }
}
