// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>The conversation type that is being created.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum CreateDmConversationRequest_conversation_type
  {
    [EnumMember(Value = "Group")]
#pragma warning disable CS1591
    Group,
#pragma warning restore CS1591
  }
}
