// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// At least one of `tweet_id`, `tweet_ids` is required.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class CreateUsersBookmarkRequest : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>Optional ID of the Bookmark folder to add the Post(s) to. When omitted, Posts are added to the user&apos;s top-level Bookmarks only. A bulk request uses this one folder for every ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? FolderId { get; set; }
#nullable restore
#else
    public string FolderId { get; set; }
#endif
    /// <summary>The ID of the Post to add to the user&apos;s Bookmarks. Mutually exclusive with `tweet_ids`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? TweetId { get; set; }
#nullable restore
#else
    public string TweetId { get; set; }
#endif
    /// <summary>Post IDs to add to the user&apos;s Bookmarks. At most 25. Mutually exclusive with `tweet_id`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<string>? TweetIds { get; set; }
#nullable restore
#else
    public List<string> TweetIds { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.CreateUsersBookmarkRequest"/> and sets the default values.
    /// </summary>
    public CreateUsersBookmarkRequest()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.CreateUsersBookmarkRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.CreateUsersBookmarkRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.CreateUsersBookmarkRequest();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "folder_id", n => { FolderId = n.GetStringValue(); } },
                { "tweet_id", n => { TweetId = n.GetStringValue(); } },
                { "tweet_ids", n => { TweetIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteStringValue("folder_id", FolderId);
      writer.WriteStringValue("tweet_id", TweetId);
      writer.WriteCollectionOfPrimitiveValues<string>("tweet_ids", TweetIds);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
