// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class CreateMediaMetadataMetadata : IAdditionalDataHolder, IParsable
#pragma warning restore CS1591
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>The allow_download_status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAllowDownloadStatus? AllowDownloadStatus { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAllowDownloadStatus AllowDownloadStatus { get; set; }
#endif
    /// <summary>The alt_text property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAltText? AltText { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAltText AltText { get; set; }
#endif
    /// <summary>The audience_policy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_audience_policy? AudiencePolicy { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_audience_policy AudiencePolicy { get; set; }
#endif
    /// <summary>The content_expiration property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataContentExpiration? ContentExpiration { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataContentExpiration ContentExpiration { get; set; }
#endif
    /// <summary>The domain_restrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataDomainRestrictions? DomainRestrictions { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataDomainRestrictions DomainRestrictions { get; set; }
#endif
    /// <summary>The found_media_origin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataFoundMediaOrigin? FoundMediaOrigin { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataFoundMediaOrigin FoundMediaOrigin { get; set; }
#endif
    /// <summary>The geo_restrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_geo_restrictions? GeoRestrictions { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_geo_restrictions GeoRestrictions { get; set; }
#endif
    /// <summary>The management_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataManagementInfo? ManagementInfo { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataManagementInfo ManagementInfo { get; set; }
#endif
    /// <summary>The preview_image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataPreviewImage? PreviewImage { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataPreviewImage PreviewImage { get; set; }
#endif
    /// <summary>The sensitive_media_warning property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_sensitive_media_warning? SensitiveMediaWarning { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_sensitive_media_warning SensitiveMediaWarning { get; set; }
#endif
    /// <summary>The shared_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataSharedInfo? SharedInfo { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataSharedInfo SharedInfo { get; set; }
#endif
    /// <summary>The sticker_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataStickerInfo? StickerInfo { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataStickerInfo StickerInfo { get; set; }
#endif
    /// <summary>The upload_source property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataUploadSource? UploadSource { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataUploadSource UploadSource { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata"/> and sets the default values.
    /// </summary>
    public CreateMediaMetadataMetadata()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "allow_download_status", n => { AllowDownloadStatus = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAllowDownloadStatus>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAllowDownloadStatus.CreateFromDiscriminatorValue); } },
                { "alt_text", n => { AltText = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAltText>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAltText.CreateFromDiscriminatorValue); } },
                { "audience_policy", n => { AudiencePolicy = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_audience_policy>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_audience_policy.CreateFromDiscriminatorValue); } },
                { "content_expiration", n => { ContentExpiration = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataContentExpiration>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataContentExpiration.CreateFromDiscriminatorValue); } },
                { "domain_restrictions", n => { DomainRestrictions = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataDomainRestrictions>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataDomainRestrictions.CreateFromDiscriminatorValue); } },
                { "found_media_origin", n => { FoundMediaOrigin = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataFoundMediaOrigin>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataFoundMediaOrigin.CreateFromDiscriminatorValue); } },
                { "geo_restrictions", n => { GeoRestrictions = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_geo_restrictions>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_geo_restrictions.CreateFromDiscriminatorValue); } },
                { "management_info", n => { ManagementInfo = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataManagementInfo>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataManagementInfo.CreateFromDiscriminatorValue); } },
                { "preview_image", n => { PreviewImage = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataPreviewImage>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataPreviewImage.CreateFromDiscriminatorValue); } },
                { "sensitive_media_warning", n => { SensitiveMediaWarning = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_sensitive_media_warning>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_sensitive_media_warning.CreateFromDiscriminatorValue); } },
                { "shared_info", n => { SharedInfo = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataSharedInfo>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataSharedInfo.CreateFromDiscriminatorValue); } },
                { "sticker_info", n => { StickerInfo = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataStickerInfo>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataStickerInfo.CreateFromDiscriminatorValue); } },
                { "upload_source", n => { UploadSource = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataUploadSource>(global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataUploadSource.CreateFromDiscriminatorValue); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAllowDownloadStatus>("allow_download_status", AllowDownloadStatus);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataAltText>("alt_text", AltText);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_audience_policy>("audience_policy", AudiencePolicy);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataContentExpiration>("content_expiration", ContentExpiration);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataDomainRestrictions>("domain_restrictions", DomainRestrictions);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataFoundMediaOrigin>("found_media_origin", FoundMediaOrigin);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_geo_restrictions>("geo_restrictions", GeoRestrictions);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataManagementInfo>("management_info", ManagementInfo);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataPreviewImage>("preview_image", PreviewImage);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadata_sensitive_media_warning>("sensitive_media_warning", SensitiveMediaWarning);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataSharedInfo>("shared_info", SharedInfo);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataStickerInfo>("sticker_info", StickerInfo);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.CreateMediaMetadataMetadataUploadSource>("upload_source", UploadSource);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
