// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>Recurrence frequency.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum CreateScheduledBroadcastRecurrence_frequency
  {
    [EnumMember(Value = "Daily")]
#pragma warning disable CS1591
    Daily,
#pragma warning restore CS1591
    [EnumMember(Value = "Weekly")]
#pragma warning disable CS1591
    Weekly,
#pragma warning restore CS1591
  }
}
