// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class DeleteChatMessagesRequest : IAdditionalDataHolder, IParsable
#pragma warning restore CS1591
  {
    /// <summary>Cryptographic signatures for the action.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesActionSignatures>? ActionSignatures { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesActionSignatures> ActionSignatures { get; set; }
#endif
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>delete_for_all removes the messages for every participant; delete_for_self removes them only from the authenticated user&apos;s view.</summary>
    public global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesRequest_delete_message_action? DeleteMessageAction { get; set; }
    /// <summary>Hash keys of encrypted media blobs to delete alongside the messages (delete_for_all only).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<string>? MediaHashKeys { get; set; }
#nullable restore
#else
    public List<string> MediaHashKeys { get; set; }
#endif
    /// <summary>Sequence IDs of the messages to delete.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<string>? SequenceIds { get; set; }
#nullable restore
#else
    public List<string> SequenceIds { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesRequest"/> and sets the default values.
    /// </summary>
    public DeleteChatMessagesRequest()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesRequest();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "action_signatures", n => { ActionSignatures = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesActionSignatures>(global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesActionSignatures.CreateFromDiscriminatorValue)?.AsList(); } },
                { "delete_message_action", n => { DeleteMessageAction = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesRequest_delete_message_action>(); } },
                { "media_hash_keys", n => { MediaHashKeys = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "sequence_ids", n => { SequenceIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesActionSignatures>("action_signatures", ActionSignatures);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.DeleteChatMessagesRequest_delete_message_action>("delete_message_action", DeleteMessageAction);
      writer.WriteCollectionOfPrimitiveValues<string>("media_hash_keys", MediaHashKeys);
      writer.WriteCollectionOfPrimitiveValues<string>("sequence_ids", SequenceIds);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
