// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>delete_for_all removes the messages for every participant; delete_for_self removes them only from the authenticated user&apos;s view.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum DeleteChatMessagesRequest_delete_message_action
  {
    [EnumMember(Value = "delete_for_all")]
#pragma warning disable CS1591
    Delete_for_all,
#pragma warning restore CS1591
    [EnumMember(Value = "delete_for_self")]
#pragma warning disable CS1591
    Delete_for_self,
#pragma warning restore CS1591
  }
}
