// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>The media category of the upload.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum InitializeMediaUploadRequest_media_category
  {
    [EnumMember(Value = "amplify_video")]
#pragma warning disable CS1591
    Amplify_video,
#pragma warning restore CS1591
    [EnumMember(Value = "tweet_gif")]
#pragma warning disable CS1591
    Tweet_gif,
#pragma warning restore CS1591
    [EnumMember(Value = "tweet_image")]
#pragma warning disable CS1591
    Tweet_image,
#pragma warning restore CS1591
    [EnumMember(Value = "tweet_video")]
#pragma warning disable CS1591
    Tweet_video,
#pragma warning restore CS1591
    [EnumMember(Value = "dm_gif")]
#pragma warning disable CS1591
    Dm_gif,
#pragma warning restore CS1591
    [EnumMember(Value = "dm_image")]
#pragma warning disable CS1591
    Dm_image,
#pragma warning restore CS1591
    [EnumMember(Value = "dm_video")]
#pragma warning disable CS1591
    Dm_video,
#pragma warning restore CS1591
    [EnumMember(Value = "subtitles")]
#pragma warning disable CS1591
    Subtitles,
#pragma warning restore CS1591
  }
}
