// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class MediaUploadRequest : IParsable
#pragma warning restore CS1591
  {
    /// <summary>Comma-separated list of user IDs who can use this media.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? AdditionalOwners { get; set; }
#nullable restore
#else
    public string AdditionalOwners { get; set; }
#endif
    /// <summary>The media file to upload: base64-encoded in JSON bodies, raw bytes in multipart bodies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media? Media { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media Media { get; set; }
#endif
    /// <summary>The category of the media being uploaded.</summary>
    public global::XbyOpenApi.Core.Client.Models.MediaUploadRequest_media_category? MediaCategory { get; set; }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.MediaUploadRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.MediaUploadRequest();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "additional_owners", n => { AdditionalOwners = n.GetStringValue(); } },
                { "media", n => { Media = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media>(global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media.CreateFromDiscriminatorValue); } },
                { "media_category", n => { MediaCategory = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.MediaUploadRequest_media_category>(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteStringValue("additional_owners", AdditionalOwners);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media>("media", Media);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.MediaUploadRequest_media_category>("media_category", MediaCategory);
    }
    /// <summary>
    /// Composed type wrapper for classes <see cref="byte"/> array, <see cref="byte"/> array
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MediaUploadRequest_media : IComposedTypeWrapper, IParsable
    {
      /// <summary>Composed type representation for type <see cref="byte"/> array</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public byte[]? Base64 { get; set; }
#nullable restore
#else
      public byte[] Base64 { get; set; }
#endif
      /// <summary>Composed type representation for type <see cref="byte"/> array</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
      public byte[]? Binary { get; set; }
#nullable restore
#else
      public byte[] Binary { get; set; }
#endif
      /// <summary>
      /// Creates a new instance of the appropriate class based on discriminator value
      /// </summary>
      /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media"/></returns>
      /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
      public static global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media CreateFromDiscriminatorValue(IParseNode parseNode)
      {
        if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
        var result = new global::XbyOpenApi.Core.Client.Models.MediaUploadRequest.MediaUploadRequest_media();
        if (parseNode.GetByteArrayValue() is byte[] base64Value)
        {
          result.Base64 = base64Value;
        }
        else if (parseNode.GetByteArrayValue() is byte[] binaryValue)
        {
          result.Binary = binaryValue;
        }
        return result;
      }
      /// <summary>
      /// The deserialization information for the current model
      /// </summary>
      /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
      public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
      {
        return new Dictionary<string, Action<IParseNode>>();
      }
      /// <summary>
      /// Serializes information the current object
      /// </summary>
      /// <param name="writer">Serialization writer to use to serialize this model</param>
      public virtual void Serialize(ISerializationWriter writer)
      {
        if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
        if (Base64 != null)
        {
          writer.WriteByteArrayValue(null, Base64);
        }
        else if (Binary != null)
        {
          writer.WriteByteArrayValue(null, Binary);
        }
      }
    }
  }
}
#pragma warning restore CS0618
