// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class MediaUploadResponseData : IAdditionalDataHolder, IParsable
#pragma warning restore CS1591
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>Seconds until the upload session expires.</summary>
    public int? ExpiresAfterSecs { get; set; }
    /// <summary>Unique identifier of the media.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Id { get; set; }
#nullable restore
#else
    public string Id { get; set; }
#endif
    /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataImage? Image { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataImage Image { get; set; }
#endif
    /// <summary>The media key for the uploaded media.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? MediaKey { get; set; }
#nullable restore
#else
    public string MediaKey { get; set; }
#endif
    /// <summary>The processing_info property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataProcessingInfo? ProcessingInfo { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataProcessingInfo ProcessingInfo { get; set; }
#endif
    /// <summary>Total size of the media in bytes.</summary>
    public int? Size { get; set; }
    /// <summary>The video property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataVideo? Video { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataVideo Video { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadResponseData"/> and sets the default values.
    /// </summary>
    public MediaUploadResponseData()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.MediaUploadResponseData"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.MediaUploadResponseData CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.MediaUploadResponseData();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "expires_after_secs", n => { ExpiresAfterSecs = n.GetIntValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image", n => { Image = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataImage>(global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataImage.CreateFromDiscriminatorValue); } },
                { "media_key", n => { MediaKey = n.GetStringValue(); } },
                { "processing_info", n => { ProcessingInfo = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataProcessingInfo>(global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataProcessingInfo.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "video", n => { Video = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataVideo>(global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataVideo.CreateFromDiscriminatorValue); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteIntValue("expires_after_secs", ExpiresAfterSecs);
      writer.WriteStringValue("id", Id);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataImage>("image", Image);
      writer.WriteStringValue("media_key", MediaKey);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataProcessingInfo>("processing_info", ProcessingInfo);
      writer.WriteIntValue("size", Size);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.MediaUploadResponseDataVideo>("video", Video);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
