// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class News : IAdditionalDataHolder, IParsable
#pragma warning restore CS1591
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>The category property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Category { get; set; }
#nullable restore
#else
    public string Category { get; set; }
#endif
    /// <summary>The cluster_posts_results property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.Search>? ClusterPostsResults { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.Search> ClusterPostsResults { get; set; }
#endif
    /// <summary>The contexts property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.News_contexts? Contexts { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.News_contexts Contexts { get; set; }
#endif
    /// <summary>The disclaimer property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Disclaimer { get; set; }
#nullable restore
#else
    public string Disclaimer { get; set; }
#endif
    /// <summary>The hook property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Hook { get; set; }
#nullable restore
#else
    public string Hook { get; set; }
#endif
    /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Id { get; set; }
#nullable restore
#else
    public string Id { get; set; }
#endif
    /// <summary>The keywords property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.News_keywords? Keywords { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.News_keywords Keywords { get; set; }
#endif
    /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Name { get; set; }
#nullable restore
#else
    public string Name { get; set; }
#endif
    /// <summary>The summary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Summary { get; set; }
#nullable restore
#else
    public string Summary { get; set; }
#endif
    /// <summary>The updated_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? UpdatedAt { get; set; }
#nullable restore
#else
    public string UpdatedAt { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.News"/> and sets the default values.
    /// </summary>
    public News()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.News"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.News CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.News();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "category", n => { Category = n.GetStringValue(); } },
                { "cluster_posts_results", n => { ClusterPostsResults = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Search>(global::XbyOpenApi.Core.Client.Models.Search.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contexts", n => { Contexts = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.News_contexts>(global::XbyOpenApi.Core.Client.Models.News_contexts.CreateFromDiscriminatorValue); } },
                { "disclaimer", n => { Disclaimer = n.GetStringValue(); } },
                { "hook", n => { Hook = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "keywords", n => { Keywords = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.News_keywords>(global::XbyOpenApi.Core.Client.Models.News_keywords.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "summary", n => { Summary = n.GetStringValue(); } },
                { "updated_at", n => { UpdatedAt = n.GetStringValue(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteStringValue("category", Category);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Search>("cluster_posts_results", ClusterPostsResults);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.News_contexts>("contexts", Contexts);
      writer.WriteStringValue("disclaimer", Disclaimer);
      writer.WriteStringValue("hook", Hook);
      writer.WriteStringValue("id", Id);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.News_keywords>("keywords", Keywords);
      writer.WriteStringValue("name", Name);
      writer.WriteStringValue("summary", Summary);
      writer.WriteStringValue("updated_at", UpdatedAt);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
