// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// Per-model scoring breakdown for the Community Note.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class NoteScoringStatus : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>Whether the caller has access to the scoring details.</summary>
    public bool? HasAccess { get; set; }
    /// <summary>Rating counts broken down per scoring model.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.NoteScoringStatus_rating_counts_per_model>? RatingCountsPerModel { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.NoteScoringStatus_rating_counts_per_model> RatingCountsPerModel { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.NoteScoringStatus"/> and sets the default values.
    /// </summary>
    public NoteScoringStatus()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.NoteScoringStatus"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.NoteScoringStatus CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.NoteScoringStatus();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "has_access", n => { HasAccess = n.GetBoolValue(); } },
                { "rating_counts_per_model", n => { RatingCountsPerModel = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.NoteScoringStatus_rating_counts_per_model>(global::XbyOpenApi.Core.Client.Models.NoteScoringStatus_rating_counts_per_model.CreateFromDiscriminatorValue)?.AsList(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteBoolValue("has_access", HasAccess);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.NoteScoringStatus_rating_counts_per_model>("rating_counts_per_model", RatingCountsPerModel);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
