// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>The GeoJSON geometry type.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum PostGeo_coordinates_type
  {
    [EnumMember(Value = "Point")]
#pragma warning disable CS1591
    Point,
#pragma warning restore CS1591
  }
}
