// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// The location tagged on the Post, if the user provided one.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class PostGeo : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>A GeoJSON Point geometry.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.PostGeo_coordinates? Coordinates { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.PostGeo_coordinates Coordinates { get; set; }
#endif
    /// <summary>The unique identifier of the tagged place.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? PlaceId { get; set; }
#nullable restore
#else
    public string PlaceId { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.PostGeo"/> and sets the default values.
    /// </summary>
    public PostGeo()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.PostGeo"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.PostGeo CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.PostGeo();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "coordinates", n => { Coordinates = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.PostGeo_coordinates>(global::XbyOpenApi.Core.Client.Models.PostGeo_coordinates.CreateFromDiscriminatorValue); } },
                { "place_id", n => { PlaceId = n.GetStringValue(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.PostGeo_coordinates>("coordinates", Coordinates);
      writer.WriteStringValue("place_id", PlaceId);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
