// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// Composed type wrapper for classes <see cref="global::XbyOpenApi.Core.Client.Models.PostDeleteComplianceSchema"/>, <see cref="global::XbyOpenApi.Core.Client.Models.PostDropComplianceSchema"/>, <see cref="global::XbyOpenApi.Core.Client.Models.PostEditComplianceSchema"/>, <see cref="global::XbyOpenApi.Core.Client.Models.PostUndropComplianceSchema"/>, <see cref="global::XbyOpenApi.Core.Client.Models.PostWithheldComplianceSchema"/>
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class PostComplianceData : IComposedTypeWrapper, IParsable
  {
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.PostDeleteComplianceSchema"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.PostDeleteComplianceSchema? PostDeleteComplianceSchema { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.PostDeleteComplianceSchema PostDeleteComplianceSchema { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.PostDropComplianceSchema"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.PostDropComplianceSchema? PostDropComplianceSchema { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.PostDropComplianceSchema PostDropComplianceSchema { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.PostEditComplianceSchema"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.PostEditComplianceSchema? PostEditComplianceSchema { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.PostEditComplianceSchema PostEditComplianceSchema { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.PostUndropComplianceSchema"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.PostUndropComplianceSchema? PostUndropComplianceSchema { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.PostUndropComplianceSchema PostUndropComplianceSchema { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.PostWithheldComplianceSchema"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.PostWithheldComplianceSchema? PostWithheldComplianceSchema { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.PostWithheldComplianceSchema PostWithheldComplianceSchema { get; set; }
#endif
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.PostComplianceData"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.PostComplianceData CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
      var result = new global::XbyOpenApi.Core.Client.Models.PostComplianceData();
      if ("PostDeleteComplianceSchema".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.PostDeleteComplianceSchema = new global::XbyOpenApi.Core.Client.Models.PostDeleteComplianceSchema();
      }
      else if ("PostDropComplianceSchema".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.PostDropComplianceSchema = new global::XbyOpenApi.Core.Client.Models.PostDropComplianceSchema();
      }
      else if ("PostEditComplianceSchema".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.PostEditComplianceSchema = new global::XbyOpenApi.Core.Client.Models.PostEditComplianceSchema();
      }
      else if ("PostUndropComplianceSchema".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.PostUndropComplianceSchema = new global::XbyOpenApi.Core.Client.Models.PostUndropComplianceSchema();
      }
      else if ("PostWithheldComplianceSchema".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.PostWithheldComplianceSchema = new global::XbyOpenApi.Core.Client.Models.PostWithheldComplianceSchema();
      }
      return result;
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      if (PostDeleteComplianceSchema != null)
      {
        return PostDeleteComplianceSchema.GetFieldDeserializers();
      }
      else if (PostDropComplianceSchema != null)
      {
        return PostDropComplianceSchema.GetFieldDeserializers();
      }
      else if (PostEditComplianceSchema != null)
      {
        return PostEditComplianceSchema.GetFieldDeserializers();
      }
      else if (PostUndropComplianceSchema != null)
      {
        return PostUndropComplianceSchema.GetFieldDeserializers();
      }
      else if (PostWithheldComplianceSchema != null)
      {
        return PostWithheldComplianceSchema.GetFieldDeserializers();
      }
      return new Dictionary<string, Action<IParseNode>>();
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      if (PostDeleteComplianceSchema != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.PostDeleteComplianceSchema>(null, PostDeleteComplianceSchema);
      }
      else if (PostDropComplianceSchema != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.PostDropComplianceSchema>(null, PostDropComplianceSchema);
      }
      else if (PostEditComplianceSchema != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.PostEditComplianceSchema>(null, PostEditComplianceSchema);
      }
      else if (PostUndropComplianceSchema != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.PostUndropComplianceSchema>(null, PostUndropComplianceSchema);
      }
      else if (PostWithheldComplianceSchema != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.PostWithheldComplianceSchema>(null, PostWithheldComplianceSchema);
      }
    }
  }
}
#pragma warning restore CS0618
