// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// Composed type wrapper for classes <see cref="global::XbyOpenApi.Core.Client.Models.DisallowedResourceProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.FieldHydrationFailureProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.FieldUnauthorizedProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.InternalErrorProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.InvalidRequestProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.NotAuthorizedForFieldProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.NotAuthorizedForResourceProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.ResourceNotFoundProblem"/>, <see cref="global::XbyOpenApi.Core.Client.Models.ResourceUnavailableProblem"/>
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class Problem : IComposedTypeWrapper, IParsable
  {
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.DisallowedResourceProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.DisallowedResourceProblem? DisallowedResourceProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.DisallowedResourceProblem DisallowedResourceProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.FieldHydrationFailureProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.FieldHydrationFailureProblem? FieldHydrationFailureProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.FieldHydrationFailureProblem FieldHydrationFailureProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.FieldUnauthorizedProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.FieldUnauthorizedProblem? FieldUnauthorizedProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.FieldUnauthorizedProblem FieldUnauthorizedProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.InternalErrorProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.InternalErrorProblem? InternalErrorProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.InternalErrorProblem InternalErrorProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.InvalidRequestProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.InvalidRequestProblem? InvalidRequestProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.InvalidRequestProblem InvalidRequestProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.NotAuthorizedForFieldProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.NotAuthorizedForFieldProblem? NotAuthorizedForFieldProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.NotAuthorizedForFieldProblem NotAuthorizedForFieldProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.NotAuthorizedForResourceProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.NotAuthorizedForResourceProblem? NotAuthorizedForResourceProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.NotAuthorizedForResourceProblem NotAuthorizedForResourceProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.ResourceNotFoundProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.ResourceNotFoundProblem? ResourceNotFoundProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.ResourceNotFoundProblem ResourceNotFoundProblem { get; set; }
#endif
    /// <summary>Composed type representation for type <see cref="global::XbyOpenApi.Core.Client.Models.ResourceUnavailableProblem"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.ResourceUnavailableProblem? ResourceUnavailableProblem { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.ResourceUnavailableProblem ResourceUnavailableProblem { get; set; }
#endif
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Problem"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.Problem CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
      var result = new global::XbyOpenApi.Core.Client.Models.Problem();
      if ("https://api.x.com/2/problems/disallowed-resource".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.DisallowedResourceProblem = new global::XbyOpenApi.Core.Client.Models.DisallowedResourceProblem();
      }
      else if ("https://api.x.com/2/problems/field-hydration-failure".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.FieldHydrationFailureProblem = new global::XbyOpenApi.Core.Client.Models.FieldHydrationFailureProblem();
      }
      else if ("https://api.x.com/2/problems/field-unauthorized".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.FieldUnauthorizedProblem = new global::XbyOpenApi.Core.Client.Models.FieldUnauthorizedProblem();
      }
      else if ("https://api.x.com/2/problems/internal-error".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.InternalErrorProblem = new global::XbyOpenApi.Core.Client.Models.InternalErrorProblem();
      }
      else if ("https://api.x.com/2/problems/invalid-request".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.InvalidRequestProblem = new global::XbyOpenApi.Core.Client.Models.InvalidRequestProblem();
      }
      else if ("https://api.x.com/2/problems/not-authorized-for-field".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.NotAuthorizedForFieldProblem = new global::XbyOpenApi.Core.Client.Models.NotAuthorizedForFieldProblem();
      }
      else if ("https://api.x.com/2/problems/not-authorized-for-resource".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.NotAuthorizedForResourceProblem = new global::XbyOpenApi.Core.Client.Models.NotAuthorizedForResourceProblem();
      }
      else if ("https://api.x.com/2/problems/resource-not-found".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.ResourceNotFoundProblem = new global::XbyOpenApi.Core.Client.Models.ResourceNotFoundProblem();
      }
      else if ("https://api.x.com/2/problems/resource-unavailable".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
      {
        result.ResourceUnavailableProblem = new global::XbyOpenApi.Core.Client.Models.ResourceUnavailableProblem();
      }
      return result;
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      if (DisallowedResourceProblem != null)
      {
        return DisallowedResourceProblem.GetFieldDeserializers();
      }
      else if (FieldHydrationFailureProblem != null)
      {
        return FieldHydrationFailureProblem.GetFieldDeserializers();
      }
      else if (FieldUnauthorizedProblem != null)
      {
        return FieldUnauthorizedProblem.GetFieldDeserializers();
      }
      else if (InternalErrorProblem != null)
      {
        return InternalErrorProblem.GetFieldDeserializers();
      }
      else if (InvalidRequestProblem != null)
      {
        return InvalidRequestProblem.GetFieldDeserializers();
      }
      else if (NotAuthorizedForFieldProblem != null)
      {
        return NotAuthorizedForFieldProblem.GetFieldDeserializers();
      }
      else if (NotAuthorizedForResourceProblem != null)
      {
        return NotAuthorizedForResourceProblem.GetFieldDeserializers();
      }
      else if (ResourceNotFoundProblem != null)
      {
        return ResourceNotFoundProblem.GetFieldDeserializers();
      }
      else if (ResourceUnavailableProblem != null)
      {
        return ResourceUnavailableProblem.GetFieldDeserializers();
      }
      return new Dictionary<string, Action<IParseNode>>();
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      if (DisallowedResourceProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.DisallowedResourceProblem>(null, DisallowedResourceProblem);
      }
      else if (FieldHydrationFailureProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.FieldHydrationFailureProblem>(null, FieldHydrationFailureProblem);
      }
      else if (FieldUnauthorizedProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.FieldUnauthorizedProblem>(null, FieldUnauthorizedProblem);
      }
      else if (InternalErrorProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.InternalErrorProblem>(null, InternalErrorProblem);
      }
      else if (InvalidRequestProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.InvalidRequestProblem>(null, InvalidRequestProblem);
      }
      else if (NotAuthorizedForFieldProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.NotAuthorizedForFieldProblem>(null, NotAuthorizedForFieldProblem);
      }
      else if (NotAuthorizedForResourceProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.NotAuthorizedForResourceProblem>(null, NotAuthorizedForResourceProblem);
      }
      else if (ResourceNotFoundProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.ResourceNotFoundProblem>(null, ResourceNotFoundProblem);
      }
      else if (ResourceUnavailableProblem != null)
      {
        writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.ResourceUnavailableProblem>(null, ResourceUnavailableProblem);
      }
    }
  }
}
#pragma warning restore CS0618
