// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum ResourceUnavailableProblem_type
#pragma warning restore CS1591
  {
    [EnumMember(Value = "https://api.x.com/2/problems/resource-unavailable")]
#pragma warning disable CS1591
    HttpsApiXCom2ProblemsResourceUnavailable,
#pragma warning restore CS1591
  }
}
