// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>The current state of the Space.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum Space_state
  {
    [EnumMember(Value = "live")]
#pragma warning disable CS1591
    Live,
#pragma warning restore CS1591
    [EnumMember(Value = "scheduled")]
#pragma warning disable CS1591
    Scheduled,
#pragma warning restore CS1591
    [EnumMember(Value = "ended")]
#pragma warning disable CS1591
    Ended,
#pragma warning restore CS1591
  }
}
