// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// Per-client-app daily Post usage entry.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class Tweets : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>Unique identifier of the client app.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? ClientAppId { get; set; }
#nullable restore
#else
    public string ClientAppId { get; set; }
#endif
    /// <summary>Daily usage entries for this client app.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.Tweets_usage>? Usage { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.Tweets_usage> Usage { get; set; }
#endif
    /// <summary>Number of daily usage entries returned for this client app.</summary>
    public long? UsageResultCount { get; set; }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.Tweets"/> and sets the default values.
    /// </summary>
    public Tweets()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Tweets"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.Tweets CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.Tweets();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "client_app_id", n => { ClientAppId = n.GetStringValue(); } },
                { "usage", n => { Usage = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Tweets_usage>(global::XbyOpenApi.Core.Client.Models.Tweets_usage.CreateFromDiscriminatorValue)?.AsList(); } },
                { "usage_result_count", n => { UsageResultCount = n.GetLongValue(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteStringValue("client_app_id", ClientAppId);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.Tweets_usage>("usage", Usage);
      writer.WriteLongValue("usage_result_count", UsageResultCount);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
