// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// The note request suggestions for the post.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class Tweet_note_request_suggestions : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>Represent the portion of text recognized as a URL, and its start and end position within the text.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.UrlEntity? SourceLink { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.UrlEntity SourceLink { get; set; }
#endif
    /// <summary>The text of the note request suggestion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Suggestion { get; set; }
#nullable restore
#else
    public string Suggestion { get; set; }
#endif
    /// <summary>The unique identifier of the note request suggestion.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? SuggestionId { get; set; }
#nullable restore
#else
    public string SuggestionId { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.Tweet_note_request_suggestions"/> and sets the default values.
    /// </summary>
    public Tweet_note_request_suggestions()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.Tweet_note_request_suggestions"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.Tweet_note_request_suggestions CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.Tweet_note_request_suggestions();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "source_link", n => { SourceLink = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.UrlEntity>(global::XbyOpenApi.Core.Client.Models.UrlEntity.CreateFromDiscriminatorValue); } },
                { "suggestion", n => { Suggestion = n.GetStringValue(); } },
                { "suggestion_id", n => { SuggestionId = n.GetStringValue(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.UrlEntity>("source_link", SourceLink);
      writer.WriteStringValue("suggestion", Suggestion);
      writer.WriteStringValue("suggestion_id", SuggestionId);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
