// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class UpdateBotRequest : IParsable
#pragma warning restore CS1591
  {
    /// <summary>New display name.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? DisplayName { get; set; }
#nullable restore
#else
    public string DisplayName { get; set; }
#endif
    /// <summary>Who may send Direct Messages to the bot.</summary>
    public global::XbyOpenApi.Core.Client.Models.UpdateBotRequest_dm_permission? DmPermission { get; set; }
    /// <summary>New handle (X screen name): 5-15 characters, letters, numbers, or underscores.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Handle { get; set; }
#nullable restore
#else
    public string Handle { get; set; }
#endif
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.UpdateBotRequest"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.UpdateBotRequest CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.UpdateBotRequest();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "display_name", n => { DisplayName = n.GetStringValue(); } },
                { "dm_permission", n => { DmPermission = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.UpdateBotRequest_dm_permission>(); } },
                { "handle", n => { Handle = n.GetStringValue(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteStringValue("display_name", DisplayName);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.UpdateBotRequest_dm_permission>("dm_permission", DmPermission);
      writer.WriteStringValue("handle", Handle);
    }
  }
}
#pragma warning restore CS0618
