// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>Who may send Direct Messages to the bot.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum UpdateBotRequest_dm_permission
  {
    [EnumMember(Value = "everyone")]
#pragma warning disable CS1591
    Everyone,
#pragma warning restore CS1591
    [EnumMember(Value = "premium")]
#pragma warning disable CS1591
    Premium,
#pragma warning restore CS1591
    [EnumMember(Value = "no_one")]
#pragma warning disable CS1591
    No_one,
#pragma warning restore CS1591
  }
}
