// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum UsageCapExceededProblem_scope
#pragma warning restore CS1591
  {
    [EnumMember(Value = "Account")]
#pragma warning disable CS1591
    Account,
#pragma warning restore CS1591
    [EnumMember(Value = "Product")]
#pragma warning disable CS1591
    Product,
#pragma warning restore CS1591
  }
}
