// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// A problem that indicates that a usage cap has been exceeded.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class UsageCapExceededProblem : global::XbyOpenApi.Core.Client.Models.Problem, IParsable
  {
    /// <summary>The period property</summary>
    public global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem_period? Period { get; set; }
    /// <summary>The scope property</summary>
    public global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem_scope? Scope { get; set; }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static new global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public override IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>(base.GetFieldDeserializers())
            {
                { "period", n => { Period = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem_period>(); } },
                { "scope", n => { Scope = n.GetEnumValue<global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem_scope>(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public override void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      base.Serialize(writer);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem_period>("period", Period);
      writer.WriteEnumValue<global::XbyOpenApi.Core.Client.Models.UsageCapExceededProblem_scope>("scope", Scope);
    }
  }
}
#pragma warning restore CS0618
