// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>
  /// Entities found in the User&apos;s bio.
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class UserEntities_description : IAdditionalDataHolder, IParsable
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>The cashtags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_cashtags>? Cashtags { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_cashtags> Cashtags { get; set; }
#endif
    /// <summary>The hashtags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_hashtags>? Hashtags { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_hashtags> Hashtags { get; set; }
#endif
    /// <summary>The mentions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_mentions>? Mentions { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_mentions> Mentions { get; set; }
#endif
    /// <summary>The urls property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_urls>? Urls { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.UserEntities_description_urls> Urls { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.UserEntities_description"/> and sets the default values.
    /// </summary>
    public UserEntities_description()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.UserEntities_description"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.UserEntities_description CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.UserEntities_description();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "cashtags", n => { Cashtags = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_cashtags>(global::XbyOpenApi.Core.Client.Models.UserEntities_description_cashtags.CreateFromDiscriminatorValue)?.AsList(); } },
                { "hashtags", n => { Hashtags = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_hashtags>(global::XbyOpenApi.Core.Client.Models.UserEntities_description_hashtags.CreateFromDiscriminatorValue)?.AsList(); } },
                { "mentions", n => { Mentions = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_mentions>(global::XbyOpenApi.Core.Client.Models.UserEntities_description_mentions.CreateFromDiscriminatorValue)?.AsList(); } },
                { "urls", n => { Urls = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_urls>(global::XbyOpenApi.Core.Client.Models.UserEntities_description_urls.CreateFromDiscriminatorValue)?.AsList(); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_cashtags>("cashtags", Cashtags);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_hashtags>("hashtags", Hashtags);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_mentions>("mentions", Mentions);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.UserEntities_description_urls>("urls", Urls);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
