// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public partial class User : IAdditionalDataHolder, IParsable
#pragma warning restore CS1591
  {
    /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
    public IDictionary<string, object> AdditionalData { get; set; }
    /// <summary>Metadata about a user&apos;s affiliation.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.UserAffiliation? Affiliation { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.UserAffiliation Affiliation { get; set; }
#endif
    /// <summary>The confirmed_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? ConfirmedEmail { get; set; }
#nullable restore
#else
    public string ConfirmedEmail { get; set; }
#endif
    /// <summary>Returns detailed information about the relationship between two users.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public List<global::XbyOpenApi.Core.Client.Models.StreamObject>? ConnectionStatus { get; set; }
#nullable restore
#else
    public List<global::XbyOpenApi.Core.Client.Models.StreamObject> ConnectionStatus { get; set; }
#endif
    /// <summary>Creation time of this User.</summary>
    public DateTimeOffset? CreatedAt { get; set; }
    /// <summary>The text of this User&apos;s profile description (also known as bio), if the User provided one.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Description { get; set; }
#nullable restore
#else
    public string Description { get; set; }
#endif
    /// <summary>A list of metadata found in the User&apos;s profile description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.UserEntities? Entities { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.UserEntities Entities { get; set; }
#endif
    /// <summary>Unique identifier of this User.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Id { get; set; }
#nullable restore
#else
    public string Id { get; set; }
#endif
    /// <summary>Indicates if this User has completed identity verification.</summary>
    public bool? IsIdentityVerified { get; set; }
    /// <summary>The location specified in the User&apos;s profile, if the User provided one. As this is a freeform value, it may not indicate a valid location.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Location { get; set; }
#nullable restore
#else
    public string Location { get; set; }
#endif
    /// <summary>Unique identifier of this User&apos;s most recent Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? MostRecentPostId { get; set; }
#nullable restore
#else
    public string MostRecentPostId { get; set; }
#endif
    /// <summary>The friendly name of this User, as shown on their profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Name { get; set; }
#nullable restore
#else
    public string Name { get; set; }
#endif
    /// <summary>Indicates if this User is a parody account.</summary>
    public bool? Parody { get; set; }
    /// <summary>Unique identifier of this User&apos;s pinned Post.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? PinnedPostId { get; set; }
#nullable restore
#else
    public string PinnedPostId { get; set; }
#endif
    /// <summary>The URL to the profile banner for this User.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? ProfileBannerUrl { get; set; }
#nullable restore
#else
    public string ProfileBannerUrl { get; set; }
#endif
    /// <summary>The URL to the profile image for this User.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? ProfileImageUrl { get; set; }
#nullable restore
#else
    public string ProfileImageUrl { get; set; }
#endif
    /// <summary>Indicates if this User has chosen to protect their Posts (in other words, if this User&apos;s Posts are private).</summary>
    public bool? Protected { get; set; }
    /// <summary>A list of metrics for this User.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.UserPublicMetrics? PublicMetrics { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.UserPublicMetrics PublicMetrics { get; set; }
#endif
    /// <summary>Indicates if you can send a DM to this User.</summary>
    public bool? ReceivesYourDm { get; set; }
    /// <summary>Indicates if this User subscribes to you.</summary>
    public bool? SubscribesToYou { get; set; }
    /// <summary>The subscription relationship between this User and you.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.UserSubscription? Subscription { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.UserSubscription Subscription { get; set; }
#endif
    /// <summary>The X Blue subscription type of the user, e.g.: Basic, Premium, PremiumPlus or None.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? SubscriptionType { get; set; }
#nullable restore
#else
    public string SubscriptionType { get; set; }
#endif
    /// <summary>The URL specified in the User&apos;s profile.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Url { get; set; }
#nullable restore
#else
    public string Url { get; set; }
#endif
    /// <summary>The X handle (screen name) of this User.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? Username { get; set; }
#nullable restore
#else
    public string Username { get; set; }
#endif
    /// <summary>Indicates if this User is a verified X User.</summary>
    public bool? Verified { get; set; }
    /// <summary>The number of verified followers of this User.</summary>
    public int? VerifiedFollowersCount { get; set; }
    /// <summary>The X Blue verified type of the user, e.g.: blue, government, business or none.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public string? VerifiedType { get; set; }
#nullable restore
#else
    public string VerifiedType { get; set; }
#endif
    /// <summary>Withholding details for withheld content.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
    public global::XbyOpenApi.Core.Client.Models.UserWithheld? Withheld { get; set; }
#nullable restore
#else
    public global::XbyOpenApi.Core.Client.Models.UserWithheld Withheld { get; set; }
#endif
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Models.User"/> and sets the default values.
    /// </summary>
    public User()
    {
      AdditionalData = new Dictionary<string, object>();
    }
    /// <summary>
    /// Creates a new instance of the appropriate class based on discriminator value
    /// </summary>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Models.User"/></returns>
    /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
    public static global::XbyOpenApi.Core.Client.Models.User CreateFromDiscriminatorValue(IParseNode parseNode)
    {
      if (ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
      return new global::XbyOpenApi.Core.Client.Models.User();
    }
    /// <summary>
    /// The deserialization information for the current model
    /// </summary>
    /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
    public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
    {
      return new Dictionary<string, Action<IParseNode>>
            {
                { "affiliation", n => { Affiliation = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.UserAffiliation>(global::XbyOpenApi.Core.Client.Models.UserAffiliation.CreateFromDiscriminatorValue); } },
                { "confirmed_email", n => { ConfirmedEmail = n.GetStringValue(); } },
                { "connection_status", n => { ConnectionStatus = n.GetCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.StreamObject>(global::XbyOpenApi.Core.Client.Models.StreamObject.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "entities", n => { Entities = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.UserEntities>(global::XbyOpenApi.Core.Client.Models.UserEntities.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "is_identity_verified", n => { IsIdentityVerified = n.GetBoolValue(); } },
                { "location", n => { Location = n.GetStringValue(); } },
                { "most_recent_post_id", n => { MostRecentPostId = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "parody", n => { Parody = n.GetBoolValue(); } },
                { "pinned_post_id", n => { PinnedPostId = n.GetStringValue(); } },
                { "profile_banner_url", n => { ProfileBannerUrl = n.GetStringValue(); } },
                { "profile_image_url", n => { ProfileImageUrl = n.GetStringValue(); } },
                { "protected", n => { Protected = n.GetBoolValue(); } },
                { "public_metrics", n => { PublicMetrics = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.UserPublicMetrics>(global::XbyOpenApi.Core.Client.Models.UserPublicMetrics.CreateFromDiscriminatorValue); } },
                { "receives_your_dm", n => { ReceivesYourDm = n.GetBoolValue(); } },
                { "subscribes_to_you", n => { SubscribesToYou = n.GetBoolValue(); } },
                { "subscription", n => { Subscription = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.UserSubscription>(global::XbyOpenApi.Core.Client.Models.UserSubscription.CreateFromDiscriminatorValue); } },
                { "subscription_type", n => { SubscriptionType = n.GetStringValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "username", n => { Username = n.GetStringValue(); } },
                { "verified", n => { Verified = n.GetBoolValue(); } },
                { "verified_followers_count", n => { VerifiedFollowersCount = n.GetIntValue(); } },
                { "verified_type", n => { VerifiedType = n.GetStringValue(); } },
                { "withheld", n => { Withheld = n.GetObjectValue<global::XbyOpenApi.Core.Client.Models.UserWithheld>(global::XbyOpenApi.Core.Client.Models.UserWithheld.CreateFromDiscriminatorValue); } },
            };
    }
    /// <summary>
    /// Serializes information the current object
    /// </summary>
    /// <param name="writer">Serialization writer to use to serialize this model</param>
    public virtual void Serialize(ISerializationWriter writer)
    {
      if (ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.UserAffiliation>("affiliation", Affiliation);
      writer.WriteStringValue("confirmed_email", ConfirmedEmail);
      writer.WriteCollectionOfObjectValues<global::XbyOpenApi.Core.Client.Models.StreamObject>("connection_status", ConnectionStatus);
      writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
      writer.WriteStringValue("description", Description);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.UserEntities>("entities", Entities);
      writer.WriteStringValue("id", Id);
      writer.WriteBoolValue("is_identity_verified", IsIdentityVerified);
      writer.WriteStringValue("location", Location);
      writer.WriteStringValue("most_recent_post_id", MostRecentPostId);
      writer.WriteStringValue("name", Name);
      writer.WriteBoolValue("parody", Parody);
      writer.WriteStringValue("pinned_post_id", PinnedPostId);
      writer.WriteStringValue("profile_banner_url", ProfileBannerUrl);
      writer.WriteStringValue("profile_image_url", ProfileImageUrl);
      writer.WriteBoolValue("protected", Protected);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.UserPublicMetrics>("public_metrics", PublicMetrics);
      writer.WriteBoolValue("receives_your_dm", ReceivesYourDm);
      writer.WriteBoolValue("subscribes_to_you", SubscribesToYou);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.UserSubscription>("subscription", Subscription);
      writer.WriteStringValue("subscription_type", SubscriptionType);
      writer.WriteStringValue("url", Url);
      writer.WriteStringValue("username", Username);
      writer.WriteBoolValue("verified", Verified);
      writer.WriteIntValue("verified_followers_count", VerifiedFollowersCount);
      writer.WriteStringValue("verified_type", VerifiedType);
      writer.WriteObjectValue<global::XbyOpenApi.Core.Client.Models.UserWithheld>("withheld", Withheld);
      writer.WriteAdditionalData(AdditionalData);
    }
  }
}
#pragma warning restore CS0618
