// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Models
{
  /// <summary>The scope of the withholding. Only present, with the value &quot;user&quot;, when the entire User is withheld.</summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public enum UserWithheld_scope
  {
    [EnumMember(Value = "user")]
#pragma warning disable CS1591
    User,
#pragma warning restore CS1591
  }
}
