// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Users.By.Username.Item;
namespace XbyOpenApi.Core.Client.Two.Users.By.Username
{
  /// <summary>
  /// Builds and executes requests for operations under \2\users\by\username
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class UsernameRequestBuilder : BaseRequestBuilder
  {
    /// <summary>Gets an item from the XbyOpenApi.Core.Client.Two.users.by.username.item collection</summary>
    /// <param name="position">A username.</param>
    /// <returns>A <see cref="global::XbyOpenApi.Core.Client.Two.Users.By.Username.Item.WithUsernameItemRequestBuilder"/></returns>
    public global::XbyOpenApi.Core.Client.Two.Users.By.Username.Item.WithUsernameItemRequestBuilder this[string position]
    {
      get
      {
        var urlTplParams = new Dictionary<string, object>(PathParameters);
        urlTplParams.Add("username", position);
        return new global::XbyOpenApi.Core.Client.Two.Users.By.Username.Item.WithUsernameItemRequestBuilder(urlTplParams, RequestAdapter);
      }
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Users.By.Username.UsernameRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public UsernameRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/users/by/username", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Users.By.Username.UsernameRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public UsernameRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/users/by/username", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
