// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Two.Users.Item.Blocking
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum GetExpansionsQueryParameterType
#pragma warning restore CS1591
  {
    [EnumMember(Value = "affiliation")]
#pragma warning disable CS1591
    Affiliation,
#pragma warning restore CS1591
    [EnumMember(Value = "most_recent_post_id")]
#pragma warning disable CS1591
    Most_recent_post_id,
#pragma warning restore CS1591
    [EnumMember(Value = "pinned_post_id")]
#pragma warning disable CS1591
    Pinned_post_id,
#pragma warning restore CS1591
  }
}
