// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
using XbyOpenApi.Core.Client.Two.Likes.Compliance;
using XbyOpenApi.Core.Client.Two.Likes.Firehose;
using XbyOpenApi.Core.Client.Two.Likes.Sample10;
namespace XbyOpenApi.Core.Client.Two.Likes
{
  /// <summary>
  /// Builds and executes requests for operations under \2\likes
  /// </summary>
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
  public partial class LikesRequestBuilder : BaseRequestBuilder
  {
    /// <summary>The compliance property</summary>
    public global::XbyOpenApi.Core.Client.Two.Likes.Compliance.ComplianceRequestBuilder Compliance
    {
      get => new global::XbyOpenApi.Core.Client.Two.Likes.Compliance.ComplianceRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The firehose property</summary>
    public global::XbyOpenApi.Core.Client.Two.Likes.Firehose.FirehoseRequestBuilder Firehose
    {
      get => new global::XbyOpenApi.Core.Client.Two.Likes.Firehose.FirehoseRequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>The sample10 property</summary>
    public global::XbyOpenApi.Core.Client.Two.Likes.Sample10.Sample10RequestBuilder Sample10
    {
      get => new global::XbyOpenApi.Core.Client.Two.Likes.Sample10.Sample10RequestBuilder(PathParameters, RequestAdapter);
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Likes.LikesRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="pathParameters">Path parameters for the request</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public LikesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/likes", pathParameters)
    {
    }
    /// <summary>
    /// Instantiates a new <see cref="global::XbyOpenApi.Core.Client.Two.Likes.LikesRequestBuilder"/> and sets the default values.
    /// </summary>
    /// <param name="rawUrl">The raw URL to use for the request builder.</param>
    /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
    public LikesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/2/likes", rawUrl)
    {
    }
  }
}
#pragma warning restore CS0618
