// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Two.Spaces.Item
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum GetSpaceFieldsQueryParameterType
#pragma warning restore CS1591
  {
    [EnumMember(Value = "created_at")]
#pragma warning disable CS1591
    Created_at,
#pragma warning restore CS1591
    [EnumMember(Value = "ended_at")]
#pragma warning disable CS1591
    Ended_at,
#pragma warning restore CS1591
    [EnumMember(Value = "id")]
#pragma warning disable CS1591
    Id,
#pragma warning restore CS1591
    [EnumMember(Value = "is_ticketed")]
#pragma warning disable CS1591
    Is_ticketed,
#pragma warning restore CS1591
    [EnumMember(Value = "lang")]
#pragma warning disable CS1591
    Lang,
#pragma warning restore CS1591
    [EnumMember(Value = "participant_count")]
#pragma warning disable CS1591
    Participant_count,
#pragma warning restore CS1591
    [EnumMember(Value = "scheduled_start")]
#pragma warning disable CS1591
    Scheduled_start,
#pragma warning restore CS1591
    [EnumMember(Value = "started_at")]
#pragma warning disable CS1591
    Started_at,
#pragma warning restore CS1591
    [EnumMember(Value = "state")]
#pragma warning disable CS1591
    State,
#pragma warning restore CS1591
    [EnumMember(Value = "subscriber_count")]
#pragma warning disable CS1591
    Subscriber_count,
#pragma warning restore CS1591
    [EnumMember(Value = "title")]
#pragma warning disable CS1591
    Title,
#pragma warning restore CS1591
    [EnumMember(Value = "updated_at")]
#pragma warning disable CS1591
    Updated_at,
#pragma warning restore CS1591
  }
}
