// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace XbyOpenApi.Core.Client.Two.Dm_events.Item
{
  [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
#pragma warning disable CS1591
  public enum GetExpansionsQueryParameterType
#pragma warning restore CS1591
  {
    [EnumMember(Value = "attachments.media_keys")]
#pragma warning disable CS1591
    AttachmentsMedia_keys,
#pragma warning restore CS1591
    [EnumMember(Value = "participant_ids")]
#pragma warning disable CS1591
    Participant_ids,
#pragma warning restore CS1591
    [EnumMember(Value = "referenced_posts")]
#pragma warning disable CS1591
    Referenced_posts,
#pragma warning restore CS1591
    [EnumMember(Value = "sender_id")]
#pragma warning disable CS1591
    Sender_id,
#pragma warning restore CS1591
  }
}
